### PR TITLE
[RA-191] Implementation of OAuth through ApiFest for File Download

### PR DESCRIPTION
**Pull request by srdjanradovic-skrill**
We needed to pass the authorization token aside of OAuth2 described way.
This is needed so the file download could work with AJAX.
One solution was passing the access_token as a query parameter on any apifest endpoint.

### CODE REVIEW

**Comment by rossitsaborissova** [comment]
Can you please explain the problem you face in details (it will be nice if you can send me example code)?

**Comment by srdjanradovic-skrill** [comment]
Hi Rossita,

During frontend transition from code written in rails to the angular, it has been decided to make CSV files on platform. Earlier, CSV had been created on FE.
In order to provide the same functionality of downloading CSV file from angular using AJAX, we had to pass authorization token to the ApiFest, somehow.
Because we use GET request, we aren’t able to send authorization token through the request header. So, one accepted solution was to pass authorization token
through the GET request as a query parameter to ApiFest endpoint. This PR has those changes.

You can see task on Jira on https://jira.skrill.net/browse/RA-191 and https://jira.skrill.net/browse/RA-56
If you have more questions, feel free to contact me.

Best,
Srdjan Radovic

**Comment by rossitsaborissova** [comment]
Hi, Srdjan
I took a look at the tasks you have linked. However, I don't see any reason why the access token could not be sent along with GET request - there is nothing special about the "Authorization Bearer [access_token]" header.

**Comment by matjaz** [comment]
Hey Rossitsa,

We want to download a file from platform **directly from browser** from single page app. Download access must be authorised.
Due the browser security limitations we can’t use AJAX to download files, so from browser we must send **plain GET request** (same as click on link). That request can not contain custom headers (Authorization header). So we need another way to pass credentials.

Paul Amor agreed that we can pass auth data as query string param. So we added access_token query param.

The code for this is pretty simple:

    location.href = platformBaseUrl + 'file_download?access_token=' + access_token;

**Comment by rossitsaborissova** [comment]
Hi, Matjaz

I think you face the problem with CORS - https://en.wikipedia.org/wiki/Cross-origin_resource_sharing. "CORS defines a way in which a browser and server can interact to safely determine whether or not to allow the cross-origin request." - the case when you send the AJAX request to another domain.
The code you have pasted, adding a query parameter, is clear and simple but I was asking for the code that generates the AJAX call. Please, send me that piece of code so I can reproduce the problem.
Adding the access token as a query parameter is not a solution as it does not obey to the OAuth20 standard.

**Comment by matjaz** [comment]
We have already solved CORS issues and are using AJAX (strictly speaking Skrill Angular SDK) for call platform.
But in this case we can not use AJAX since this is file download. We are using above approach using `location.href`. See http://stackoverflow.com/questions/8771342/file-download-script-doesnt-work-when-called-from-ajax

**Comment by PaulAmor** [comment]
Hi Rossitsa, 

What is the objection that you have, just for OAuth20? 

In RFC6750 section 2.3 (http://tools.ietf.org/html/rfc6750) it does say that it is compliant but not the recommended solution to send in the token as a URI parameter. In this case as it was a OTP then the risks associated with this that they mention should be mitigated.

Please let me know you concerns.

**Comment by matjaz** [comment]
Paul, thanks for the reference to RFC. Actually we've implemented access_token as described in this RFC. It would be more secure to use OTP which is valid only for one request, but then again using OTP is not "by the standard".

**Comment by rossitsaborissova** [comment]
Hi, all

My concerns are:
1. passing the access token as a query parameter is a security breach as it is stated in RFC6750:
"Because of the security weaknesses associated with the URI method
   (see Section 5), including the high likelihood that the URL
   containing the access token will be logged, it SHOULD NOT be used
   unless it is impossible to transport the access token in the
   "Authorization" request header field or the HTTP request entity-body.
   Resource servers MAY support this method."
2. changing the normal/standard way a system works(ApiFest in that case) in order to solve a problem another 
application faces is not a right solution. I know it's easier when it is an open project but did you research all the possibilities to solve the problem?

**Comment by matjaz** [comment]
Looking at [RFC 6750](http://tools.ietf.org/html/rfc6750#section-2) I would say all three options (GET, POST, header) are by the "standard". So point 2 is irrelevant.
We can't use headers in this scenario.
So I see two options here:
1. keep simple [GET request](http://tools.ietf.org/html/rfc6750#section-2.3), but use OTP, which is valid only for one request for short time (max few 10 sec). Google and Amazon are using this.
2. change to [POST request](http://tools.ietf.org/html/rfc6750#section-2.2) and pass access_token in request body.

Is any of this solutions acceptable?

There were other solutions discussed in an email thread (including  [request signing](http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html)), but general consensus was we don't want to introduce yet another authentication mechanism.

**Comment by PaulAmor** [comment]
Given the above list I suggest that we attempt to use POST to pass the token, it is not strictly clean either  because downloading a document does not change the state of the server so should not require a POST request, but it will avoid problems with the logging mentioned in the RFC.

If this is not possible then we should use GET, based on creating a token with much reduced scope to limit the risk.

Is that acceptable to everybody?

**Comment by rossitsaborissova** [comment]
"2. change to POST request and pass access_token in request body." - I still don't understand why the access token cannot be passed as a header, the standard usage or I didn't get it right.

**Comment by matjaz** [comment]
Browser can send custom headers (Authorization in this case) only using XHR/AJAX. But using XHR, browser can not prompt user to save a file to disk.
So for file download we must do plain GET or POST, which does not support custom headers.

Paul's idea is acceptable for me. Rossitsa, thoughts?

**Comment by rossitsaborissova** [comment]
Parsing the request body in order to extract the access token, then validating it and continue with the mapping will sloooow down the whole process so that is not acceptable for me.
Can you paste the angularjs code you are about to use - the one that does not work and the simple GET/POST? There should be a way to save a file without changing the flow in the ApiFest.

**Comment by matjaz** [comment]
I doubt parsing body would significantly slowdown request parsing, since this is a fallback option if Authorization header is missing.

This is current implementation using GET passing access_token in query string:
`SkrillAuthenticationService` & `SkrillCommunicationService` are services from Skrill Angular SDK.

    that.export = function() {
      var id = this.id;
      SkrillAuthenticationService.getUserToken().then(function(response) {
        var config = {
          resource: '/me/mass-payments/' + id + '/export?access_token=' +
                      $window.encodeURIComponent(response.accessToken)
        };
        SkrillCommunicationService.prepareRequestUrl(config);
        $window.location.href = config.url;
      });
    };

I am really keen to find a solution to download a file, passing Authorization header, directly from browser, so any clues are very much welcome!

**Comment by matjaz** [comment]
A decision has been made we'll go with [body parameter](http://tools.ietf.org/html/rfc6750#section-2.2).

**Pull request closed without merging**
